/**
 * GONZAGA ELÉTRICA - Banco de Dados Modular (V8.0)
 */
const produtos = [
    { nome: "Painel 24W Quadrado Embutir BF/BN/BQ", categoria: "iluminacao", sku: "painelembquad24wbf", imagem: "img/3.jpg", galeria: ["img/3.jpg", "img/4.jpg", "img/8.jpg"], badges: ["Bivolt", "Pronta Entrega"], relacionados: ["luminaria-linear-36w", "painelembred24wbf"], especificacoes: { material: "Alumínio/Policarbonato", tamanho: "30x30cm", watts: "24W/18W/12W", cor: "Branco Frio, Branco neutro e Branco quente", tensao: "Bivolt" } },
    { nome: "Painel 24W Redondo Embutir BF/BN/BQ", categoria: "iluminacao", sku: "painelembred24wbf", imagem: "img/4.jpg", especificacoes: { tamanho: "Ø 30cm", watts: "24W/18W/12W", cor: "Branco Frio, Branco neutro e Branco quente", tensao: "Bivolt" } },
    { nome: "Painel 24W Quadrado Sobrepor BF/BN/BQ", categoria: "iluminacao", sku: "paineisobrequad24wbf", imagem: "img/8.jpg", especificacoes: { tamanho: "30x30cm", watts: "24W/18W/12W", cor: "Branco Frio, Branco neutro e Branco quente",tensao: "Bivolt" } },
    { nome: "Painel 24W Redondo Sobrepor BF/BN/BQ", categoria: "iluminacao", sku: "paineisobrered24wbf", imagem: "img/13.jpeg", especificacoes: { tamanho: "Ø 30cm", watts: "24W/18W/12W", cor: "Branco Frio, Branco neutro e Branco quente", tensao: "Bivolt" } },
    { nome: "Luminária Linear LED Slim 36W", categoria: "iluminacao", sku: "luminaria-linear-36w", imagem: "img/lampadalinear36w.jpeg", especificacoes: { tamanho: "120cm", watts: "36W", cor: "Branco Frio", tensao: "Bivolt" } },
    { nome: "Luminária Linear LED Slim Pequena", categoria: "iluminacao", sku: "luminaria-linear-pequena", imagem: "img/lampadalinearpequena.jpeg", especificacoes: { tamanho: "60cm", watts: "18W", cor: "Branco Frio", tensao: "Bivolt" } },
    { nome: "Kit Trilho Eletrificado com 3 Spots LED", categoria: "iluminacao", sku: "trilho-eletrificado-kit", imagem: "img/trilhoeletrificado.jpg", especificacoes: { tamanho: "1 Metro", spots: "3 Inclusos", cor: "Preto Fosco", tensao: "Bivolt" } },
    { nome: "Trilho Eletrificado de Alumínio (Avulso)", categoria: "iluminacao", sku: "trilho-eletrificado-avulso", imagem: "img/trilhosozinho.jpg", especificacoes: { tamanho: "1m / 2m", material: "Alumínio", cor: "Preto" } },
    { nome: "Spot Orientável para Trilho Eletrificado", categoria: "iluminacao", sku: "spot-avulso-trilho", imagem: "img/lampada_trilho.webp", especificacoes: { articulacao: "360°", cor: "Preto Fosco", tensao: "Bivolt" } },
    { nome: "Spot Embutir Redondo LED 12W Luz Amarela", categoria: "iluminacao", sku: "spot-inspire-red-12w", imagem: "img/spot_de_embutir_led_12w_luz_amarela_inspire_bivolt_89691091_0490_300x300.jpeg", especificacoes: { tamanho: "Ø 12cm", watts: "12W", cor: "Amarela (3000K)", tensao: "Bivolt" } },
    { nome: "Spot Embutir Quadrado LED 12W Luz Amarela", categoria: "iluminacao", sku: "spot-quad-12w-am", imagem: "img/spot_de_embutir_led_12w_luz_amarela_inspire_bivolt_89691112_5c44_300x300.jpeg", especificacoes: { tamanho: "12x12cm", watts: "12W", cor: "Amarela (3000K)", tensao: "Bivolt" } },
    { nome: "Spot Embutir Quadrado LED 5W Luz Branca", categoria: "iluminacao", sku: "spot-inspire-quad-5w-bf", imagem: "img/spot_de_embutir_led_5w_luz_branca_inspire_bivolt_89691084_8772_300x300.jpeg", especificacoes: { tamanho: "9x9cm", watts: "5W", cor: "Branco Frio", tensao: "Bivolt" } },
    { nome: "Fita LED COB 12V 3000K 5 Metros", categoria: "iluminacao", sku: "fita-led-cob-3k", imagem: "img/fita_cob_12v_9w_ip20_3000k_900lm_5m_91841106_0004_300x300.jpg", especificacoes: { tamanho: "5m", watts: "9W/m", cor: "Branco Quente", tensao: "12V DC" } },
    { nome: "Lâmpada LED Bulbo Elgin 40W Alta Potência", categoria: "iluminacao", sku: "lamp-led-elgin-40w", imagem: "img/lampada_de_led_e27_bulbo_40w_3200lm_branca_91093681_1a2b_300x300.jpg", especificacoes: { base: "E27", watts: "40W", lumens: "3200 lm", cor: "Branco Frio" } },
    { nome: "Disjuntor Termomagnético Monopolar DIN", categoria: "eletrica", sku: "disjuntor-tramontina-mono", imagem: "img/disjuntor.jpeg", galeria: ["img/disjuntor.jpeg", "img/disjuntor2.jpeg"], badges: ["Tramontina (Original)", "Uso Industrial", "Pronta Entrega"], relacionados: ["disjuntor-tramontina-bi", "caixa-disjuntor-steck"], especificacoes: { marca: "Tramontina", corrente: "10A a 63A", curva: "C", tensao: "127V/220V" } },
    { nome: "Disjuntor Termomagnético Bipolar DIN", categoria: "eletrica", sku: "disjuntor-tramontina-bi", imagem: "img/disjuntor2.jpeg", especificacoes: { marca: "Tramontina", corrente: "20A a 80A", curva: "C", tensao: "220V/380V" } },
    { nome: "Disjuntor Geral Tripolar DIN Industrial", categoria: "eletrica", sku: "disjuntor-tramontina-tri", imagem: "img/disjuntor3.jpeg", especificacoes: { marca: "Tramontina", corrente: "40A a 100A", curva: "C", tensao: "220V/380V/440V" } },
    { nome: "Disjuntor Caixa Moldada NEMA Preto", categoria: "eletrica", sku: "disjuntor-industrial-preto", imagem: "img/download.jpeg", especificacoes: { marca: "Soprano/GE", tipo: "Caixa Moldada", cor: "Preto" } },
    { nome: "Quadro de Distribuição de Embutir", categoria: "eletrica", sku: "caixa-disjuntor-steck", imagem: "img/caixadisjuntorsteck.jpeg", especificacoes: { marca: "Steck", capacidade: "4 a 36 módulos", cor: "Branca/Fumê" } },
    { nome: "Barramento Elétrico Neutro / Terra", categoria: "eletrica", sku: "barramento-neutro-terra", imagem: "img/barramento.jpeg", especificacoes: { material: "Cobre", conexoes: "6 a 12 parafusos", corrente_max: "80A" } },
    { nome: "Chave de Fenda e Phillips Profissional", categoria: "ferramentas", sku: "chave-fenda-philips-combo", imagem: "img/chavefenda.jpeg", especificacoes: { material: "Aço Cromo Vanádio", cabo: "Isolado" } },
    { nome: "Broca para Parede e Concreto Videa", categoria: "ferramentas", sku: "broca-parede-videa", imagem: "img/brocaparede.jpeg", especificacoes: { tipo: "Videa Alvenaria", encaixe: "Mandril Padrão" } }
];